### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by Sarahjsts**

### CODE REVIEW

**Comment by Nosferatul** [comment]
Hey, can you squash your commit? check https://docs.coala.io/en/latest/Developers/Git_Basics.html

**Comment by Sarahjsts** [comment]
I'm trying to,  I'm just having some difficulty. My apologies.

**Comment by aptrishu** [comment]
@Sarahjsts 
If you are facing any difficulty just ask on our channel ("https://gitter.im/coala/coala"). You'll get your answers. :)

**Comment by Sarahjsts** [comment]
I think I fixed the issue I was having with the commits.

**Comment by Mariatta** [comment]
ack aea7938

**Comment by Mariatta** [comment]
@rultor merge

**Comment by Mariatta** [comment]
@rultor merge

**Comment by Mixih** [comment]
@rultor merge

**Comment by Mixih** [comment]
wait this guy needs a rebase now to be mergable.....

**Comment by Mixih** [comment]
unack aea7938

**Comment by sils** [comment]
ack aea7938

It's all good, we're not that picky for this repo. Mind that the commit message wouldn't be ok for most other coala repos but for this one we don't enforce the guidelines strictly.

**Pull request merged**
