### PR TITLE
More Info: Add planet URL

### PR DESCRIPTION
**Pull request by sils**
Needs to be approved by @fneu after planet.coala-analyzer.org is properly rerouted.

### CODE REVIEW

**Comment by sils** [comment]
@fneu and donate.coala-analyzer.org too

**Comment by fneu** [comment]
can I still ask rultor to merge this?

**Comment by fneu** [comment]
@sils1297 seems like it is not configured for this repo?

**Comment by sils** [comment]
Yes, merge manually please, we dont care about history mich for this one..
Yet

**Pull request merged**
