### PR TITLE
add deprecation note

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Review by prnvdixit — COMMENTED** [review]
@KrishMunot Maybe something like the one at https://github.com/coala/bear-docs? Mention the new website url __&__ it's corresponding repository to aid someone looking for contributing to that. 👍 😄

**Review by prnvdixit — COMMENTED** [review]
@KrishMunot Are you working on this issue? In that case, first assign yourself the issue please...

**Comment by KrishMunot** [comment]
@prnvdixit Updated the commit

**Comment by prnvdixit** [comment]
Changes look fine to me. Just squash your commits into one.
Also, go through https://coala.io/commit and change your commit accordingly - Use ```git commit -a --amend``` to do the same.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
